/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as JuegoRouteImport } from './routes/juego.tsx'
import { Route as HistoriaRouteImport } from './routes/historia.tsx'
import { Route as AyudaRouteImport } from './routes/ayuda.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'

const JuegoRoute = JuegoRouteImport.update({
  id: '/juego',
  path: '/juego',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/historia': typeof HistoriaRoute
  '/juego': typeof JuegoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/historia': typeof HistoriaRoute
  '/juego': typeof JuegoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/historia': typeof HistoriaRoute
  '/juego': typeof JuegoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ayuda' | '/historia' | '/juego'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ayuda' | '/historia' | '/juego'
  id: '__root__' | '/' | '/ayuda' | '/historia' | '/juego'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyudaRoute: typeof AyudaRoute
  HistoriaRoute: typeof HistoriaRoute
  JuegoRoute: typeof JuegoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/juego': {
      id: '/juego'
      path: '/juego'
      fullPath: '/juego'
      preLoaderRoute: typeof JuegoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyudaRoute: AyudaRoute,
  HistoriaRoute: HistoriaRoute,
  JuegoRoute: JuegoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
